import { type NextPage } from "next";
import Head from "next/head";
import { SignupForm, type signupFormSchema } from "./components/SignupForm";
import { type z } from "zod";
import { api } from "@/utils/api";
import { Button } from "./components/ui/button";

const Home: NextPage = () => {
  const signup = api.user.signup.useMutation();
  const allUsers = api.user.allUsers.useQuery();

  async function onSubmit(values: z.infer<typeof signupFormSchema>) {
    await signup.mutateAsync(values);
    await allUsers.refetch();
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
            Drunk Salem
          </h1>
          <SignupForm onSubmit={onSubmit} />
          <div>
            {allUsers.data?.map((user) => (
              <Button key={user.id} variant="outline">
                {user.username}
              </Button>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
