import { type NextPage } from "next";
import Head from "next/head";
import { SignupForm, type signupFormSchema } from "./components/SignupForm";
import { api } from "@/utils/api";
import { type z } from "zod";

const Home: NextPage = () => {
  const result = api.example.hello.useQuery({ text: "world222" });

  // 2. Define a submit handler.
  function onSubmit(values: z.infer<typeof signupFormSchema>) {
    // Do something with the form values.
    // ✅ This will be type-safe and validated.
    console.log(values);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
            Drunk Salem
          </h1>
          <SignupForm onSubmit={onSubmit} />
          <p>{result.data?.greeting}</p>
        </div>
      </main>
    </>
  );
};

export default Home;
